apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-html-app
  labels:
    app: simple-html-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-html-app
  template:
    metadata:
      labels:
        app: simple-html-app
    spec:
      containers:
      - name: html-container
        image: krishnabobbepalli/simple-html-app:c7ba81b3200b9561e4f51df17b73333de5a0a633
        ports:
        - containerPort: 80