apiVersion: v1
kind: Service
metadata:
  name: simple-html-app
spec:
  type: NodePort
  selector:
    app: simple-html-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30067